# Generated by Django 5.2.3 on 2025-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DONE", "Done"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
