# Generated by Django 5.2.3 on 2025-06-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_alter_idea_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="youtube_url",
            field=models.URLField(null=True),
        ),
    ]
