# Generated by Django 5.2.3 on 2025-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0003_alter_idea_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
